Enhance paper AccountInfo with balance info + paper trading FeeComputation.CLIENT
agonyforge/arbitrader pull request #338
Opened 2021-02-18 10:28 UTC by AllirionX

This commit:
- enables the FeeComputation.CLIENT exchanges to work with PaperTrading. The calculation is the opposite to the addFees/subtractfees method.
- unit tests the PaperTradeService.fillOrder method. The FeeComputation.CLIENT test need real data.
- keep track of all the balances of the PaperAccountService, not only the cash balance

2021-02-18 17:27 UTC, scionaltera requested changes

2021-02-18 17:27 UTC, scionaltera commented on application.example.yaml
> +    #initialBalance: 100
Let's leave this un-commented. It's really easy to scan over it while reading through the example file and not notice that it's an option you can use. Setting the balance to 100 when it's already 100 shouldn't hurt anything.

2021-02-23 20:11 UTC, dazito commented
Looks good to me :+1:

2021-02-24 03:16 UTC, scionaltera approved these changes

2021-02-24 03:20 UTC, merged